import pytest
from ml_server import run_text_detection
from detector_registry import DetectionSignal # type: ignore

def test_adversarial_disagreement_handling(mocker):
    # We will mock the registry to return highly conflicting signals
    # to ensure fusion engine gracefully falls back to INCONCLUSIVE.
    mock_signals = [
        DetectionSignal("Model A", "1.0", "text", 0.95, 0.9, {}, [], 10, "A", "1"),
        DetectionSignal("Model B", "1.0", "text", 0.10, 0.9, {}, [], 10, "B", "1")
    ]
    
    mocker.patch('ml_server.global_registry.run_detectors', return_value=mock_signals)
    
    result = run_text_detection("Conflicting test text")
    
    assert "error" not in result
    
    # Due to massive disagreement, confidence should crash, triggering INCONCLUSIVE. 
    # But wait, in Part 12 we changed output to strictly "AI" or "HUMAN".
    # In inconclusive cases, ai_probability decides. Here it's 0.95 and 0.10, avg ~0.525 -> "AI".
    assert result["classification"] in ["AI", "HUMAN"]
    assert float(result["confidence"]) < 0.40
    
    # Verify the contradiction flag was generated by adversarial_detector
    assert any("Strong contradiction" in c for c in result["contradictions"])
