from provenance_engine import ProvenanceOrchestrator
import re
from typing import Any, Dict, List, Optional
from base_detector import BaseDetector
from detector_registry import DetectionSignal, DetectorRegistry
from pixel_forensics import PixelForensicsOrchestrator
from fusion_engine import EvidenceFusionEngine

# Shared metadata tag lists extracted from legacy monolith
AI_SOFTWARE_TAGS = [
    "midjourney", "stable diffusion", "stable-diffusion", "stablediffusion", "dalle", "dall-e",
    "dall-e 3", "sdxl", "sd-xl", "sd 1.5", "adobe firefly", "adobe generative", "firefly", "flux.1",
    "flux", "leonardo ai", "ideogram", "invokeai", "comfyui", "fooocus", "foocus", "automatic1111",
    "civitai", "novelai", "craiyon", "nightcafe", "krea ai", "midjourneybot", "ai generated",
    "ai-generated", "generated by ai", "genai", "generative ai", "contentcredentials:generative",
    "imagegenerator", "steps: ", "cfg scale: ", "sampler: ", "samplers: ", "denoising strength: ",
    "clip skip: ", "negative prompt", "sd_model", "sd_model_name", "model_hash", "sampler_name",
    "controlnet", "lora:", "dreambooth", "safetensors", "generation time", "class_type", "comfy",
    "workflow", "ذكاء اصطناعي", "مولد بالذكاء", "مولدة بالذكاء", "تم إنشاؤها بالذكاء", "تم انشاؤها بالذكاء",
    "محتوى اصطناعي", "صورة مولدة", "موجه:", "برومبت", "ميدجورني", "دالي", "دال إي", "ستيبل ديفيوجن", "كومفي يو آي"
]

EDITOR_SOFTWARE_TAGS = [
    "adobe photoshop", "photoshop", "camera raw", "lightroom", "capture one", "illustrator",
    "affinity photo", "gimp"
]

CAMERA_HINT_TAGS = [
    "apple", "iphone", "ipad", "samsung", "galaxy", "nikon", "canon", "sony", "fujifilm",
    "google pixel", "pixel 4", "pixel 5", "pixel 6", "pixel 7", "pixel 8", "pixel 9", "pixel xl"
]

RAW_CAPTURE_MARKERS = [
    "exif", "make", "model", "fnumber", "exposuretime", "isospeedratings", "focallength"
]

WEAK_AI_METADATA_TAGS = {
    "workflow", "class_type", "inputs", "nodes", "links", "latent", "diffusion", "synthetic"
}

STRONG_AI_CONTEXT_TAGS = [
    tag for tag in AI_SOFTWARE_TAGS if tag not in WEAK_AI_METADATA_TAGS
]

def decode_metadata_text(raw_bytes: bytes) -> str:
    if not raw_bytes:
        return ""
    if len(raw_bytes) > 2_500_000:
        raw_bytes = raw_bytes[:2_000_000] + raw_bytes[-500_000:]
    text_parts = []
    for encoding in ("utf-8", "utf-16-le"):
        try:
            text_parts.append(raw_bytes.decode(encoding, errors="ignore"))
        except Exception:
            pass
    try:
        return re.sub(
            r"[^\x09\x0a\x0d\x20-\x7E\u0600-\u06FF]+",
            " ",
            "\n".join(text_parts).replace("\x00", " "),
        ).lower()
    except Exception:
        return "\n".join(text_parts).replace("\x00", " ").lower()

def metadata_text_has_tag(raw_text: str, tag: str) -> bool:
    try:
        needle = tag.lower()
        if re.fullmatch(r"[a-z0-9-]+", needle):
            return re.search(rf"(^|[^a-z0-9]){re.escape(needle)}([^a-z0-9]|$)", raw_text) is not None
        return needle in raw_text
    except Exception:
        return tag.lower() in raw_text

class SoftwareMetadataAnalyzer(BaseDetector):
    def __init__(self):
        super().__init__("Software Metadata Analyzer", "1.0", "provenance")

    def preprocess(self, input_data: Any, context: dict) -> dict:
        # input_data is raw_bytes
        raw_text = decode_metadata_text(input_data)
        return {"raw_text": raw_text}

    def extract_features(self, preprocessed_data: dict, context: dict) -> dict:
        raw_text = preprocessed_data["raw_text"]
        if not raw_text:
            return {"failed": True, "reason": "No metadata text provided"}

        ai_tag = next((tag for tag in AI_SOFTWARE_TAGS if metadata_text_has_tag(raw_text, tag)), None)
        editor_tag = next((tag for tag in EDITOR_SOFTWARE_TAGS if metadata_text_has_tag(raw_text, tag)), None)
        
        if ai_tag in WEAK_AI_METADATA_TAGS and not any(tag in raw_text for tag in STRONG_AI_CONTEXT_TAGS):
            ai_tag = None
        
        return {
            "ai_tag_found": ai_tag,
            "editor_tag_found": editor_tag,
            "failed": False
        }

    def evaluate_signal_quality(self, features: dict, context: dict) -> float:
        if features.get("failed"):
            return 0.0
        if features.get("ai_tag_found") or features.get("editor_tag_found"):
            return 1.0
        return 0.1 # Missing metadata doesn't indicate human, it's just missing

    def predict_raw(self, features: dict, context: dict) -> float:
        if features.get("failed"):
            return 0.5
        
        if features["ai_tag_found"]:
            return 0.99
        if features["editor_tag_found"]:
            return 0.40 # Editors might indicate human drafting but can be used for AI too
            
        return 0.5

    def calibrate(self, raw_score: float, context: dict) -> float:
        return raw_score


class HardwareProvenanceAnalyzer(BaseDetector):
    def __init__(self):
        super().__init__("Hardware Provenance Analyzer", "1.0", "provenance")

    def preprocess(self, input_data: Any, context: dict) -> dict:
        raw_text = decode_metadata_text(input_data)
        return {"raw_text": raw_text}

    def extract_features(self, preprocessed_data: dict, context: dict) -> dict:
        raw_text = preprocessed_data["raw_text"]
        if not raw_text:
            return {"failed": True, "reason": "No metadata text provided"}

        camera_hint = next((tag for tag in CAMERA_HINT_TAGS if metadata_text_has_tag(raw_text, tag)), None)
        raw_capture_marker = next((tag for tag in RAW_CAPTURE_MARKERS if metadata_text_has_tag(raw_text, tag)), None)
        
        has_camera_workflow = bool(camera_hint and (raw_capture_marker or "exif" in raw_text))
        
        return {
            "camera_hint": camera_hint,
            "raw_capture_marker": raw_capture_marker,
            "has_camera_workflow": has_camera_workflow,
            "failed": False
        }

    def evaluate_signal_quality(self, features: dict, context: dict) -> float:
        if features.get("failed"):
            return 0.0
        if features.get("has_camera_workflow"):
            return 1.0
        if features.get("camera_hint"):
            return 0.5
        return 0.1

    def predict_raw(self, features: dict, context: dict) -> float:
        if features.get("failed"):
            return 0.5
            
        if features["has_camera_workflow"]:
            return 0.05 # Very strong hardware/sensor signal
        if features["camera_hint"]:
            return 0.25 # Weak hardware hint
            
        return 0.5

    def calibrate(self, raw_score: float, context: dict) -> float:
        return raw_score


class ImageProvenanceOrchestrator:
    def __init__(self):
        self.detectors = [
            SoftwareMetadataAnalyzer(),
            HardwareProvenanceAnalyzer()
        ]

    def analyze(self, raw_bytes: bytes, context: Optional[Dict[str, Any]] = None) -> List[DetectionSignal]:
        ctx = context or {}
        signals = []
        
        for det in self.detectors:
            try:
                signal = det.execute(raw_bytes, ctx)
                # Only keep signals with at least some quality, unless they are definitively 0.5 (neutral)
                if signal.signal_quality is not None and signal.signal_quality >= 0.1:
                    signals.append(signal)
            except Exception as e:
                print(f"Failed to execute {det.name}: {e}")
                
        return signals


class NeuralVisionAnalyzer(BaseDetector):
    def __init__(self):
        super().__init__("Neural Vision Analyzer", "1.0", "image")

    def preprocess(self, input_data: Any, context: dict) -> dict:
        return {}

    def extract_features(self, preprocessed_data: dict, context: dict) -> dict:
        return {"neural_prob": context.get("neural_prob", 0.5), "success": context.get("neural_model_ran", False)}

    def evaluate_signal_quality(self, features: dict, context: dict) -> float:
        return 1.0 if features.get("success") else 0.0

    def predict_raw(self, features: dict, context: dict) -> float:
        if not features.get("success"):
            return 0.5
        return features.get("neural_prob", 0.5)

    def calibrate(self, raw_score: float, context: dict) -> float:
        return raw_score

class AdvancedImageOrchestrator:
    def __init__(self):
        self.provenance_orchestrator = ProvenanceOrchestrator()
        self.pixel_orchestrator = PixelForensicsOrchestrator()
        self.vision_analyzer = NeuralVisionAnalyzer()
        self.fusion_engine = EvidenceFusionEngine()

    def analyze(self, img_pil, raw_bytes: bytes, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        ctx = context or {}
        
        # 1. Gather Provenance Signals
        provenance_signals = self.provenance_orchestrator.analyze(raw_bytes, ctx)
        
        # 2. Gather Pixel Signals
        pixel_signals = self.pixel_orchestrator.analyze(img_pil, ctx)
        
        # 3. Gather Neural Vision Signal
        vision_signal = self.vision_analyzer.execute(None, ctx)
        
        # 4. Gather Filename Signal (if present in context)
        filename_signal = None
        if ctx.get("filename_hit", False):
            class FilenameAnalyzer(BaseDetector):
                def __init__(self):
                    super().__init__("Filename Hint", "1.0", "image")
                def preprocess(self, i, c): return {}
                def extract_features(self, p, c): return {"hit": c.get("filename_hit")}
                def evaluate_signal_quality(self, f, c): return 1.0 if f["hit"] else 0.1
                def predict_raw(self, f, c): return 0.95 if f["hit"] else 0.5
                def calibrate(self, r, c): return r
            filename_signal = FilenameAnalyzer().execute(None, ctx)
        
        # Combine all signals
        all_signals = provenance_signals + pixel_signals
        if vision_signal.signal_quality > 0:
            all_signals.append(vision_signal)
        if filename_signal and filename_signal.signal_quality > 0.1:
            all_signals.append(filename_signal)
            
        meta_signal = AdversarialImageMetaAnalyzer().execute(all_signals, ctx)
        if meta_signal.signal_quality > 0:
            all_signals.append(meta_signal)
            
        # 5. Fuse using mathematically robust architecture
        fusion_result = self.fusion_engine.fuse(all_signals)
        return fusion_result


class AdversarialImageMetaAnalyzer(BaseDetector):
    def __init__(self):
        super().__init__("Adversarial Disagreement Meta-Analyzer", "1.0", "meta")

    def preprocess(self, input_data: Any, context: dict) -> dict:
        return {"signals": input_data}

    def extract_features(self, preprocessed_data: dict, context: dict) -> dict:
        signals = preprocessed_data["signals"]
        
        vision_ai = False
        pixel_human = False
        provenance_human = False
        
        for sig in signals:
            if sig.detector_name == "Neural Vision Analyzer" and sig.score > 0.8:
                vision_ai = True
            elif sig.detector_name == "Pixel Noise Analyzer" and sig.score < 0.2:
                pixel_human = True
            elif sig.detector_name == "Hardware Provenance Analyzer" and sig.score < 0.2:
                provenance_human = True
                
        if vision_ai and (pixel_human or provenance_human):
            return {"flag": "HIGH_MODEL_DISAGREEMENT", "details": "Vision model strongly predicts AI, but physical/provenance signals strongly indicate Human."}
            
        return {"flag": "NONE"}

    def evaluate_signal_quality(self, features: dict, context: dict) -> float:
        return 1.0 if features.get("flag") != "NONE" else 0.0

    def predict_raw(self, features: dict, context: dict) -> float:
        return 0.5

    def calibrate(self, raw_score: float, context: dict) -> float:
        return raw_score
