/**
 * 3truth Mandatory Disclaimer Modal & Firestore Confirmation Tracking
 * ===================================================================
 * Appears ONLY when an authenticated user logs in or signs up for the first time
 * and has not yet confirmed the AI Detection Disclaimer.
 * Does NOT appear for logged-out / guest visitors.
 * Updates Firestore user document with `isClickedConfirm: true` and `clickedConfirm: true`.
 */

(function () {
  "use strict";

  const WELCOME_NOTICE_CONFIG = {
    badgeTextEn: "LEGAL NOTICE",
    badgeTextAr: "إشعار قانوني إلزامي",
    
    titleEn: "AI Detection Disclaimer and Limitation of Liability",
    titleAr: "إخلاء مسؤولية الكشف عن الذكاء الاصطناعي وتحديد المسؤولية",
    
    subtitleEn: "Please review and acknowledge the terms of use and liability limitations before accessing 3Truth.",
    subtitleAr: "يرجى قراءة وتأكيد إخلاء المسؤولية وشروط الاستخدام قبل الدخول إلى منصة 3Truth.",

    bodyHtmlEn: `
      <div class="notice-content-inner">
        <p class="notice-lead">
          <strong>3Truth provides AI detection and analysis tools for informational and educational purposes only.</strong> The results generated by 3Truth are algorithmic estimates and do not constitute definitive, conclusive, or guaranteed determinations regarding whether content was created by a human or by artificial intelligence.
        </p>
        
        <p>
          Due to the inherent limitations and evolving nature of artificial intelligence, machine-learning systems, language models, content-generation technologies, and detection methodologies, <strong>3Truth may produce inaccurate, incomplete, inconsistent, or erroneous results, including false positives and false negatives.</strong> No detection result should be treated as absolute proof or as the sole basis for any academic, professional, employment, disciplinary, legal, financial, reputational, or other consequential decision.
        </p>
        
        <p>
          To the maximum extent permitted by applicable law, 3Truth, its owners, operators, employees, contractors, affiliates, service providers, and representatives <strong>shall not be liable for any loss, damage, claim, consequence, or adverse action</strong> arising from or relating to a user's reliance upon, interpretation of, or use of any detection result or information provided through the service.
        </p>
        
        <p>
          <strong>Users are solely responsible</strong> for independently evaluating and verifying results before relying upon them or using them to make decisions concerning any person, organization, document, or other content. Use of 3Truth's services constitutes acknowledgment and acceptance that detection results are probabilistic and may be incorrect.
        </p>
        
        <p>
          3Truth does not warrant or represent that its services will be accurate, error-free, uninterrupted, complete, reliable, or suitable for any particular purpose. No result generated by 3Truth should be construed as a factual certification, legal determination, academic finding, or definitive attribution of authorship.
        </p>
        
        <p class="notice-disclaimer">
          By accessing or using 3Truth, you acknowledge that AI detection is an inherently uncertain technological process and agree that you will not rely exclusively upon 3Truth's results when making decisions that may materially affect another person's rights, opportunities, reputation, education, employment, finances, or legal position.
        </p>
      </div>
    `,

    bodyHtmlAr: `
      <div class="notice-content-inner" dir="rtl">
        <p class="notice-lead">
          <strong>تقدم 3Truth أدوات الكشف والتحليل للذكاء الاصطناعي لأغراض إعلامية وتعليمية فقط.</strong> إن النتائج التي تصدرها 3Truth هي تقديرات خوارزمية ولا تشكل بأي حال من الأحوال قرارات نهائية أو قاطعة أو مضمونة بشأن ما إذا كان المحتوى قد تم إنشاؤه بواسطة إنسان أو بواسطة الذكاء الاصطناعي.
        </p>
        
        <p>
          نظراً للقيود الكامنة والطبيعة المتطورة باستمرار لأنظمة الذكاء الاصطناعي، ونظم التعلم الآلي، والنماذج اللغوية، وتقنيات توليد المحتوى، ومنهجيات الكشف، <strong>قد تنتج 3Truth نتائج غير دقيقة أو غير مكتملة أو غير متسقة أو خاطئة، بما في ذلك النتائج الإيجابية الخاطئة (False Positives) والنتائج السلبية الخاطئة (False Negatives).</strong> يجب عدم التعامل مع أي نتيجة فحص كدليل قاطع أو كأساس وحيد لأي قرار أكاديمي، مهني، وظيفي، تأديبي، قانوني، مالي، سمعة، أو أي قرار آخر ذي عواقب هامة.
        </p>
        
        <p>
          إلى أقصى حد يسمح به القانون المعمول به، <strong>تخلي 3Truth وملاّكها ومشغلوها وموظفوها ومقاولوها والشركات التابعة لها ومقدمو الخدمات وممثلوها مسؤوليتهم عن أي خسارة أو ضرر أو مطالبة أو نتيجة أو إجراء سلبي</strong> ينشأ عن أو يتعلق باعتماد المستخدم على أي نتيجة فحص أو تفسيرها أو استخدام أي معلومات مقدمة من خلال الخدمة.
        </p>
        
        <p>
          <strong>يتحمل المستخدمون وحدهم المسؤولية الكاملة</strong> عن التقييم والتحقق المستقل من النتائج قبل الاعتماد عليها أو استخدامها لاتخاذ قرارات تخص أي شخص أو منظمة أو وثيقة أو أي محتوى آخر. يُعد استخدام خدمات 3Truth إقراراً وقبولاً بأن نتائج الكشف احتمالية وقد تكون غير صحيحة.
        </p>
        
        <p>
          لا تضمن 3Truth أو تتعهد بأن خدماتها ستكون دقيقة أو خالية من الأخطاء أو متواصلة دون انقطاع أو كاملة أو موثوقة أو مناسبة لأي غرض معين. ولا يجوز تفسير أي نتيجة تصدرها 3Truth على أنها شهادة وقائعية، أو حكم قانوني، أو نتيجة أكاديمية، أو نسبة تأليف نهائية ومطلقة.
        </p>
        
        <p class="notice-disclaimer">
          بالوصول إلى 3Truth أو استخدامها، فإنك تقر بأن الكشف عن الذكاء الاصطناعي هو عملية تكنولوجية غير مؤكدة بطبيعتها، وتوافق على أنك لن تعتمد بشكل حصري على نتائج 3Truth عند اتخاذ قرارات قد تؤثر تأثيراً جوهرياً على حقوق أي شخص آخر، أو فرصه، أو سمعته، أو تعليمه، أو وظيفته، أو شؤونه المالية، أو وضعه القانوني.
        </p>
      </div>
    `,

    confirmBtnTextEn: "I Confirm and Read the Message",
    confirmBtnTextAr: "أقر بأنني قرأت وفهمت هذه الرسالة"
  };

  // Helper: check if language is Arabic
  function isArabicLanguage() {
    const lang = document.documentElement.lang || localStorage.getItem("language") || "en";
    return lang.toLowerCase().startsWith("ar");
  }

  // Inject Styles for the Modal
  function injectStyles() {
    if (document.getElementById("welcome-modal-styles")) return;

    const style = document.createElement("style");
    style.id = "welcome-modal-styles";
    style.textContent = `
      #mandatory-welcome-overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100vw;
        height: 100vh;
        background: rgba(2, 12, 10, 0.92);
        backdrop-filter: blur(24px);
        -webkit-backdrop-filter: blur(24px);
        z-index: 99999999;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 1.25rem;
        opacity: 0;
        visibility: hidden;
        transition: opacity 0.4s cubic-bezier(0.16, 1, 0.3, 1), visibility 0.4s;
        box-sizing: border-box;
        pointer-events: auto !important;
      }

      #mandatory-welcome-overlay.active {
        opacity: 1;
        visibility: visible;
      }

      #mandatory-welcome-card {
        position: relative;
        width: 100%;
        max-width: 740px;
        height: 85vh;
        max-height: 850px;
        background: linear-gradient(145deg, rgba(6, 45, 38, 0.98) 0%, rgba(3, 31, 26, 0.99) 100%);
        border: 1px solid rgba(47, 238, 204, 0.35);
        border-radius: 24px;
        box-shadow: 0 30px 80px rgba(0, 0, 0, 0.9), 0 0 50px rgba(47, 238, 204, 0.22);
        display: flex;
        flex-direction: column;
        overflow: hidden;
        transform: scale(0.92) translateY(20px);
        transition: transform 0.4s cubic-bezier(0.16, 1, 0.3, 1);
        color: #f8fafc;
        font-family: 'Inter', sans-serif;
        pointer-events: auto !important;
      }

      #mandatory-welcome-overlay.active #mandatory-welcome-card {
        transform: scale(1) translateY(0);
      }

      #mandatory-welcome-card::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 4px;
        background: linear-gradient(90deg, #2feecc, #38bdf8, #2feecc);
        background-size: 200% 100%;
        animation: cyberGlowMove 4s linear infinite;
        z-index: 20;
      }

      @keyframes cyberGlowMove {
        0% { background-position: 0% 0%; }
        100% { background-position: 200% 0%; }
      }

      @keyframes modalShake {
        0%, 100% { transform: translateX(0); }
        20% { transform: translateX(-12px); }
        40% { transform: translateX(12px); }
        60% { transform: translateX(-8px); }
        80% { transform: translateX(8px); }
      }

      #mandatory-welcome-card.shake {
        animation: modalShake 0.45s cubic-bezier(0.36, 0.07, 0.19, 0.97) both;
        box-shadow: 0 30px 80px rgba(0, 0, 0, 0.9), 0 0 60px rgba(239, 68, 68, 0.55);
        border-color: rgba(239, 68, 68, 0.75);
      }

      .modal-header-section {
        padding: 1.75rem 2.25rem 1.25rem 2.25rem;
        border-bottom: 1px solid rgba(47, 238, 204, 0.18);
        position: relative;
        background: rgba(2, 20, 16, 0.5);
        flex-shrink: 0;
      }

      .modal-badge {
        display: inline-flex;
        align-items: center;
        gap: 0.45rem;
        font-size: 0.75rem;
        font-weight: 800;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        color: #2feecc;
        background: rgba(47, 238, 204, 0.12);
        border: 1px solid rgba(47, 238, 204, 0.35);
        padding: 0.3rem 0.8rem;
        border-radius: 9999px;
        margin-bottom: 0.75rem;
      }

      .modal-badge-dot {
        width: 6px;
        height: 6px;
        border-radius: 50%;
        background: #2feecc;
        box-shadow: 0 0 10px #2feecc;
        animation: pulseDot 2s infinite;
      }

      @keyframes pulseDot {
        0%, 100% { opacity: 1; transform: scale(1); }
        50% { opacity: 0.35; transform: scale(0.75); }
      }

      .modal-title {
        font-family: 'Outfit', sans-serif;
        font-size: 1.45rem;
        font-weight: 800;
        color: #ffffff;
        margin: 0 0 0.35rem 0;
        line-height: 1.3;
        letter-spacing: -0.01em;
      }

      .modal-subtitle {
        font-size: 0.875rem;
        color: #94a3b8;
        margin: 0;
        line-height: 1.4;
      }

      .modal-body-section {
        padding: 1.75rem 2.25rem;
        overflow-y: auto !important;
        overflow-x: hidden;
        flex: 1 1 auto;
        min-height: 0;
        font-size: 0.95rem;
        line-height: 1.7;
        color: #cbd5e1;
        overscroll-behavior: contain !important;
        -webkit-overflow-scrolling: touch !important;
        touch-action: pan-y !important;
      }

      .modal-body-section::-webkit-scrollbar {
        width: 8px;
      }
      .modal-body-section::-webkit-scrollbar-track {
        background: rgba(0, 0, 0, 0.3);
        border-radius: 4px;
      }
      .modal-body-section::-webkit-scrollbar-thumb {
        background: rgba(47, 238, 204, 0.35);
        border-radius: 4px;
        border: 2px solid transparent;
        background-clip: content-box;
      }
      .modal-body-section::-webkit-scrollbar-thumb:hover {
        background: rgba(47, 238, 204, 0.65);
        background-clip: content-box;
      }

      .notice-lead {
        font-size: 1rem;
        color: #ffffff;
        margin-bottom: 1.15rem;
        line-height: 1.65;
      }

      .notice-content-inner p {
        margin-bottom: 1.15rem;
      }

      .notice-content-inner strong {
        color: #2feecc;
      }

      .notice-disclaimer {
        font-size: 0.875rem;
        color: #94a3b8;
        background: rgba(2, 20, 16, 0.65);
        border: 1px solid rgba(47, 238, 204, 0.22);
        border-radius: 14px;
        padding: 1.15rem 1.35rem;
        margin-top: 1.35rem;
        margin-bottom: 0.5rem;
        line-height: 1.6;
      }

      .modal-footer-section {
        padding: 1.25rem 2.25rem 1.75rem 2.25rem;
        border-top: 1px solid rgba(47, 238, 204, 0.18);
        background: rgba(2, 18, 14, 0.7);
        display: flex;
        flex-direction: column;
        gap: 0.75rem;
        flex-shrink: 0;
      }

      .modal-confirm-btn {
        width: 100%;
        padding: 1.05rem 1.75rem;
        background: linear-gradient(135deg, #2feecc 0%, #00b4d8 100%);
        color: #031f1a;
        font-family: 'Outfit', sans-serif;
        font-size: 1.05rem;
        font-weight: 800;
        letter-spacing: 0.02em;
        border: none;
        border-radius: 14px;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 0.65rem;
        box-shadow: 0 0 30px rgba(47, 238, 204, 0.4);
        transition: all 0.25s cubic-bezier(0.16, 1, 0.3, 1);
        user-select: none;
      }

      .modal-confirm-btn:hover {
        transform: translateY(-2px);
        box-shadow: 0 0 45px rgba(47, 238, 204, 0.65);
        filter: brightness(1.08);
      }

      .modal-confirm-btn:active {
        transform: translateY(0) scale(0.99);
      }

      .modal-lock-indicator {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 0.4rem;
        font-size: 0.75rem;
        color: #64748b;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        font-weight: 600;
      }

      /* RTL / Arabic typography */
      html[lang="ar"] .modal-title,
      html[lang="ar"] .modal-confirm-btn {
        font-family: 'Tajawal', 'IBM Plex Sans Arabic', sans-serif;
      }
      
      html[lang="ar"] #mandatory-welcome-card {
        text-align: right;
        direction: rtl;
      }

      @media (max-width: 640px) {
        .modal-header-section { padding: 1.25rem 1.25rem 1rem 1.25rem; }
        .modal-body-section { padding: 1.25rem 1.25rem; font-size: 0.9rem; }
        .modal-footer-section { padding: 1rem 1.25rem 1.25rem 1.25rem; }
        .modal-title { font-size: 1.2rem; }
        .modal-confirm-btn { font-size: 0.95rem; padding: 0.9rem 1rem; }
      }
    `;
    document.head.appendChild(style);
  }

  // Show the Disclaimer Modal for a specific authenticated user
  function showWelcomeModalForUser(user) {
    if (document.getElementById("mandatory-welcome-overlay")) return;

    injectStyles();

    const isAr = isArabicLanguage();
    const badgeText = isAr ? WELCOME_NOTICE_CONFIG.badgeTextAr : WELCOME_NOTICE_CONFIG.badgeTextEn;
    const title = isAr ? WELCOME_NOTICE_CONFIG.titleAr : WELCOME_NOTICE_CONFIG.titleEn;
    const subtitle = isAr ? WELCOME_NOTICE_CONFIG.subtitleAr : WELCOME_NOTICE_CONFIG.subtitleEn;
    const bodyHtml = isAr ? WELCOME_NOTICE_CONFIG.bodyHtmlAr : WELCOME_NOTICE_CONFIG.bodyHtmlEn;
    const btnText = isAr ? WELCOME_NOTICE_CONFIG.confirmBtnTextAr : WELCOME_NOTICE_CONFIG.confirmBtnTextEn;
    const lockText = isAr ? "إقرار إلزامي للمتابعة إلى المنصة" : "Mandatory acknowledgment required to proceed";

    // Create Modal HTML
    const overlay = document.createElement("div");
    overlay.id = "mandatory-welcome-overlay";
    overlay.setAttribute("role", "dialog");
    overlay.setAttribute("aria-modal", "true");
    overlay.setAttribute("aria-labelledby", "welcome-modal-title");
    overlay.setAttribute("data-lenis-prevent", "true");

    overlay.innerHTML = `
      <div id="mandatory-welcome-card" dir="${isAr ? 'rtl' : 'ltr'}" data-lenis-prevent="true">
        <div class="modal-header-section">
          <div class="modal-badge">
            <span class="modal-badge-dot"></span>
            <span>${badgeText}</span>
          </div>
          <h2 id="welcome-modal-title" class="modal-title">${title}</h2>
          <p class="modal-subtitle">${subtitle}</p>
        </div>

        <div class="modal-body-section" data-lenis-prevent="true">
          ${bodyHtml}
        </div>

        <div class="modal-footer-section">
          <button id="welcome-modal-confirm-btn" class="modal-confirm-btn" type="button">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="20 6 9 17 4 12"></polyline>
            </svg>
            <span>${btnText}</span>
          </button>
          <div class="modal-lock-indicator">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
              <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
            </svg>
            <span>${lockText}</span>
          </div>
        </div>
      </div>
    `;

    document.body.appendChild(overlay);

    // Pause Lenis smooth scrolling while modal is open
    if (window.lenis && typeof window.lenis.stop === "function") {
      window.lenis.stop();
    }

    // Lock page scroll
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    // Reveal modal with smooth transition
    setTimeout(() => {
      overlay.classList.add("active");
    }, 120);

    const card = document.getElementById("mandatory-welcome-card");
    const confirmBtn = document.getElementById("welcome-modal-confirm-btn");
    const bodySection = overlay.querySelector(".modal-body-section");

    // Prevent scroll leak to underlying page
    if (bodySection) {
      bodySection.addEventListener("wheel", function (e) {
        e.stopPropagation();
      }, { passive: true });

      bodySection.addEventListener("touchmove", function (e) {
        e.stopPropagation();
      }, { passive: true });
    }

    // Shake animation trigger when attempting to bypass
    function triggerShake() {
      if (!card) return;
      card.classList.remove("shake");
      void card.offsetWidth;
      card.classList.add("shake");
      setTimeout(() => {
        card.classList.remove("shake");
      }, 500);
    }

    // 1. Block backdrop click escape
    overlay.addEventListener("click", function (e) {
      if (e.target === overlay) {
        e.preventDefault();
        e.stopPropagation();
        triggerShake();
      }
    });

    // 2. Block Escape key
    function handleKeyDown(e) {
      if (e.key === "Escape" || e.keyCode === 27) {
        e.preventDefault();
        e.stopPropagation();
        triggerShake();
      }
    }
    window.addEventListener("keydown", handleKeyDown, true);

    // 3. Confirm button action
    confirmBtn.addEventListener("click", async function () {
      const userKey = "3truth_disclaimer_confirmed_" + user.uid;
      try {
        localStorage.setItem(userKey, "true");
      } catch (err) {
        console.warn("Could not write to localStorage:", err);
      }

      // Update Firestore user document with isClickedConfirm: true
      if (typeof firebase !== "undefined" && firebase.firestore) {
        try {
          const timestamp = firebase.firestore.FieldValue && firebase.firestore.FieldValue.serverTimestamp
            ? firebase.firestore.FieldValue.serverTimestamp()
            : new Date().toISOString();

          await firebase.firestore().collection("users").doc(user.uid).set(
            {
              isClickedConfirm: true,
              clickedConfirm: true,
              confirmedDisclaimerAt: timestamp,
            },
            { merge: true }
          );
        } catch (err) {
          console.warn("Error updating isClickedConfirm in Firestore:", err);
        }
      }

      // Cleanup listeners & restore scrolling
      window.removeEventListener("keydown", handleKeyDown, true);
      document.body.style.overflow = previousOverflow || "";

      // Resume Lenis smooth scrolling
      if (window.lenis && typeof window.lenis.start === "function") {
        window.lenis.start();
      }

      // Smooth exit animation
      overlay.classList.remove("active");
      setTimeout(() => {
        overlay.remove();
      }, 450);
    });
  }

  // Check confirmation status for an authenticated user
  async function checkAndShowForUser(user) {
    if (!user || !user.uid) return;

    const userKey = "3truth_disclaimer_confirmed_" + user.uid;
    
    // 1. Fast path: Instant check from local cache (0ms delay)
    if (localStorage.getItem(userKey) === "true") {
      return;
    }

    // 2. Database path: Verify with Firestore in case user confirmed on another device
    let isFirestoreConfirmed = false;
    if (typeof firebase !== "undefined" && firebase.firestore) {
      try {
        const docSnap = await firebase.firestore().collection("users").doc(user.uid).get();
        if (docSnap.exists) {
          const data = docSnap.data();
          if (data && (data.isClickedConfirm === true || data.clickedConfirm === true)) {
            isFirestoreConfirmed = true;
            try {
              localStorage.setItem(userKey, "true");
            } catch (e) {}
          }
        }
      } catch (err) {
        console.warn("Firestore disclaimer check warning:", err);
      }
    }

    // If confirmed in Firestore database, do NOT show modal
    if (isFirestoreConfirmed) {
      return;
    }

    // Show modal once for this signed-in user
    showWelcomeModalForUser(user);
  }

  // Listen to Firebase Auth state
  if (typeof firebase !== "undefined" && firebase.auth) {
    firebase.auth().onAuthStateChanged(function (user) {
      if (!user) {
        // User is logged out -> Do NOT show modal, remove if present
        const existing = document.getElementById("mandatory-welcome-overlay");
        if (existing) existing.remove();
        return;
      }

      // User is logged in -> Check confirmation status
      checkAndShowForUser(user);
    });
  }
})();
